image: ifjproj

build-and-test:
  stage: build
  # install the necessary build tools when needed
  #before_script:
  #  - apt update && apt -y install make zip unzip valgrind bash texlive && make clean
  script:
    - make -s test
  artifacts:
    paths:
      - build/
      - submission/
      - test_artifacts/
      - test-submission/
      - xsesta07.zip

#speed-test:
#  stage: test
#  # install the necessary build tools when needed
#  before_script:
#    - apt update && apt -y install make
#  script:
#    - make speedtest

doc:
  only:
    - master
  stage: .post
  # install the necessary build tools when needed
  #before_script:
  #  - apt update && apt -y install make doxygen texlive && make clean
  script:
    - make documentation
  artifacts:
    paths:
      - doc

