terminal:
  image: debian:latest
  before_script:
    - apt-get update && apt-get install -y make zip unzip valgrind bash doxygen texlive
#  services:
#    - name: registry.gitlab.com/gitlab-org/webide-file-sync:latest
#      alias: webide-file-sync
#      entrypoint: ["/bin/sh"]
#      command: ["-c", "sleep 5 && ./webide-file-sync -project-dir $CI_PROJECT_DIR"]
#      ports:
#        # The `webide-file-sync` executable defaults to port 3000.
#        - number: 3000
